language: c

env:
  - LUA=lua5.1
  #- LUA=lua5.2

install:
  - if [ $LUA = "lua5.1" ]; then
      sudo apt-get  install -qq lua5.1;
    fi
  - if [ $LUA = "lua5.2" ]; then
      sudo apt-get  install -qq lua5.2;
    fi
  - sudo apt-get  install luarocks
  - sudo luarocks install lua-testmore
  - sudo luarocks install lua-testlongstring
  - sudo luarocks install lzlib ZLIB_LIBDIR=/lib/x86_64-linux-gnu/
  - sudo luarocks install zipwriter
  - sudo pip install pytest
  - if [ $LUA = "lua5.1" ]; then
      sudo luarocks install bit32;
    fi

script:
  - prove --exec="$LUA" --ext=lua -r test/unit
  - py.test test/comparison/test*.py -v
